### ISSUE TITLE
[Bug] Marketplace - User: Filters not working

### ISSUE THREAD

**Issue by rohitsamagra** [COMPASS-DPG/marketplace-portal#17]
- When I apply all the filters getting the below error

![Image](https://github.com/COMPASS-DPG/marketplace-portal/assets/145356240/28b94771-29b5-4ed9-8b1f-7ba0de014b81)

**Comment by kh4l1d64** [comment]
- This is more of a frontend validation check making sure that the user enters a course name and then filters on the responses received.

**Comment by rohitsamagra** [comment]
- Search service is to get courses from BPP, filters are only applied after a name is entered
