### ISSUE TITLE
[Bug] Marketplace - User: Star button does not work

### ISSUE THREAD

**Issue by rohitsamagra** [COMPASS-DPG/marketplace-portal#18]
- Star button within courses does not work (shows error) while share button does not work, no specific action basis it

![Image](https://github.com/COMPASS-DPG/marketplace-portal/assets/145356240/149ac9f6-6655-4848-9832-b2fd4bb53257)

![Image](https://github.com/COMPASS-DPG/marketplace-portal/assets/145356240/45447a23-df98-4805-93fe-26cbbfa0a306)

**Comment by kh4l1d64** [comment]
- Pushed the fix, need to be deployed.
